image: ubuntu/20.10
packages:
  - runc
  - podman
sources:
  - https://git.sr.ht/~cadence/invidious-redirect
secrets:
  - dea6a8f9-aba8-4ecc-8ce7-bc4707b30a96
tasks:
  - build: |
      cd invidious-redirect
      podman build -t quay.io/invidious/invidious-redirect:latest .
  - push: podman push quay.io/invidious/invidious-redirect:latest
